-- SQL script to create TB_PRODUCT and TB_PROMOTION tables
DROP TABLE IF EXISTS TB_PROMOTION;
DROP TABLE IF EXISTS TB_PRODUCT;

CREATE TABLE TB_PRODUCT (
    PROD_CD VARCHAR(255) PRIMARY KEY,
    PROD_NM VARCHAR(255),
    USE_YN CHAR(1)
);

CREATE TABLE TB_PROMOTION (
    PROMO_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PROD_CD VARCHAR(255),
    PROMO_PRICE INT,
    START_DT VARCHAR(8),
    END_DT VARCHAR(8),
    FOREIGN KEY (PROD_CD) REFERENCES TB_PRODUCT(PROD_CD)
);

-- Index for performance tuning
CREATE INDEX IDX_PROMOTION_DATES ON TB_PROMOTION (START_DT, END_DT);
CREATE INDEX IDX_PRODUCT_USE_YN ON TB_PRODUCT (USE_YN);
